[project]
name = "Gyal Project"
version = "0.0.0.1"
author = "Omochain"
description = "Meu primeiro sistema operacional"

[build]
target = "x86"          # Arquitetura (32 ou 64 bits)
output = "iso/gyal.iso" # Onde a ISO vai ser gerada
entry_point = "gyal/boot.gyal" # O arquivo principal que dá o boot